### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by coolpalani** [emre141/hawkular-with-glusterfs-persistent#1]
Could you show the OpenShift inventory files where you have specified the GlusterFS details.

**Comment by emre141** [comment]
I have solved my problem thanks

**Comment by coolpalani** [comment]
I am not sure whether you read my queries or not
I am trying to deploy RedHat OpenShift Enterprise 3.7 with GlusterFS.

While I install with persistent storage (GlusterFS), what are all things I need to take care GlusterFS
I want to enable Hawkular and ELK with GlusterFS persistent storage

I am using below similar setup.

**Single Master, Single etcd, and Multiple Nodes Inventory File**

# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true

openshift_deployment_type=openshift-enterprise

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# host group for masters
[masters]
master.example.com

# host group for etcd
[etcd]
master.example.com

# host group for nodes, includes region info
[nodes]
master.example.com
node1.example.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
node2.example.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}"
infra-node1.example.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
infra-node2.example.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

In order to enable ELK,Hawkular what are all parameters need to inject in above inventory.
